In [1]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# import seaborn as sns

import math
import random
import logging
from typing import Union

# from shapely.geometry import Polygon, MultiPolygon, Point

from pygus import Urban, Species, tree_population_from_geojson, ScenarioConfig, SiteConfig, WeatherConfig

print(os.getcwd())
ALLOMETRICS = Species(os.path.join("..", "pygus", "inputs", "allometrics.json"))

/Users/jake/dev/gus-2025/notebooks
input file: ../pygus/inputs/allometrics.json
Found allometrics file! Using:  ../pygus/inputs/allometrics.json

In [2]:
population = pd.read_csv("test_pop.csv")
population.head()

,id,dbh,height,species,condition,lat,lng,xpos,ypos
0,0,1.497577,2.932639,carpinus betulus,excellent,51.496978,-0.168865,49,6
1,1,1.580488,3.045567,sorbus torminalis,excellent,51.497005,-0.169084,34,9
2,2,1.670537,3.162727,betula pendula,excellent,51.497622,-0.169388,10,77
3,3,0.953573,2.071514,quercus petraea,excellent,51.497452,-0.169274,19,58
4,4,1.171785,2.441981,cornus sanguinea,good,51.496983,-0.169058,36,6

In [3]:
Weather = WeatherConfig(growth_season_mean=153, growth_season_var=7)

site_file ="city_config.json"
site = SiteConfig(total_m2=1000,
                  impervious_m2=0,
                  pervious_m2=1000,
                  weather=Weather,
                  light_loss_multiplier=0.1)

In [4]:
scenario_low = ScenarioConfig(time_horizon_years=50, maintenance_scope = 1, contagion_level = 'low')
scenario_high = ScenarioConfig(time_horizon_years=50, maintenance_scope = 1, contagion_level = 'high')

In [5]:
proj_low = Urban(population, species_allometrics=ALLOMETRICS, site_config=site, scenario=scenario_low)

In [6]:
proj_high = Urban(population, species_allometrics=ALLOMETRICS, site_config=site, scenario=scenario_high)

In [7]:
outputs_low = proj_low.run_model()

In [8]:
outputs_high = proj_high.run_model()

In [9]:
outputs_low.tail()

,AllTrees,Storage,Seq,Avg_Seq,Released,Avg_Rel,Alive,Dead,Critical,Dying,Poor,Replaced,Seq_std,Cum_Seq
45,5297,170429.577778,4726.915352,3.830563,2055.459474,1.655951,1234,0,0,0,0,0,3.073922,169561.631116
46,5388,175140.353907,4698.235834,3.788900,1920.501319,1.546331,1240,0,0,0,0,0,3.061347,174259.866950
47,5472,179872.323974,4721.862923,3.792661,1874.124520,1.570273,1245,0,0,0,0,0,3.041930,178981.729873
48,5556,184758.426087,4874.756274,3.906055,2454.503561,1.999571,1248,0,0,0,0,0,3.155070,183856.486147
49,5630,189694.814522,4927.932637,3.967740,3235.845236,2.565169,1242,0,0,0,0,0,3.187156,188784.418784

In [10]:
outputs_high.tail()

,AllTrees,Storage,Seq,Avg_Seq,Released,Avg_Rel,Alive,Dead,Critical,Dying,Poor,Replaced,Seq_std,Cum_Seq
45,5464,164095.655129,4507.335660,3.676456,2180.127130,1.666854,1226,0,0,0,0,0,3.025715,163201.453590
46,5550,168445.879338,4339.201282,3.574301,2175.658993,1.742917,1214,0,0,0,0,0,2.941140,167540.654873
47,5645,172944.179854,4486.765139,3.659678,2131.041193,1.680170,1226,0,0,0,0,0,3.016971,172027.420012
48,5740,177333.106037,4375.933983,3.592721,2898.386304,2.520268,1218,0,0,0,0,0,2.999266,176403.353995
49,5818,181538.558421,4195.168472,3.467081,3414.051519,2.898714,1210,0,0,0,0,0,2.880522,180598.522468

In [11]:
low_agents = proj_low.get_agent_data()
high_agents = proj_high.get_agent_data()

In [12]:
low_agents.tail()

                        species       dbh    height    crownH    crownW  \
Step AgentID
50   5626          salix caprea  1.180729  2.608589  1.459160  1.283302
     5627      betula pubescens  1.228097  2.687565  1.500077  1.318396
     5628     sorbus torminalis  0.738413  1.781096  1.036995  0.923151
     5629      carpinus betulus  0.646849  1.589480  0.940558  0.841275
     5630           sorbus aria  1.289329  2.786895  1.551741  1.362767

              canopy_overlap   cle  condition   dieback   biomass  ...  \
Step AgentID                                                       ...
50   5626                0.0  0.56  EXCELLENT  0.001941  0.344096  ...
     5627                0.0  0.56  EXCELLENT  0.000552  0.375939  ...
     5628                0.0  0.56  EXCELLENT  0.003003  0.119666  ...
     5629                0.0  0.56  EXCELLENT  0.000066  0.088836  ...
     5630                0.0  0.56  EXCELLENT  0.002344  0.419438  ...

                carbon  deroot  detrunk  mulched  burnt  xpos  ypos  est_age  \
Step AgentID
50   5626     0.172048     0.0      0.0      0.0    0.0    19    65        1
     5627     0.187970     0.0      0.0      0.0    0.0    38    27        1
     5628     0.059833     0.0      0.0      0.0    0.0    32    40        1
     5629     0.044418     0.0      0.0      0.0    0.0    35    37        1
     5630     0.209719     0.0      0.0      0.0    0.0    38    23        1

                    lat       lng
Step AgentID
50   5626     51.497513 -0.169263
     5627     51.497168 -0.169023
     5628     51.497288 -0.169098
     5629     51.497261 -0.169056
     5630     51.497131 -0.169014

[5 rows x 21 columns]

In [13]:
high_agents.tail()

                       species       dbh    height    crownH    crownW  \
Step AgentID
50   5814     betula pubescens  0.507278  1.283994  0.787588  0.711640
     5815        quercus nigra  0.541175  1.733260  0.814913  0.719168
     5816       acer campestre  1.054441  2.388912  1.346010  1.186450
     5817               decidu  1.014714  2.317069  1.309196  1.154996
     5818     malus sylvestris  0.671254  1.641232  0.966564  0.863342

              canopy_overlap   cle  condition   dieback   biomass  ...  \
Step AgentID                                                       ...
50   5814                0.0  0.56  EXCELLENT  0.008087  0.051412  ...
     5815                0.0  0.56  EXCELLENT  0.000469  0.059467  ...
     5816                0.0  0.56  EXCELLENT  0.006241  0.266766  ...
     5817                0.0  0.56  EXCELLENT  0.004949  0.244681  ...
     5818                0.0  0.56  EXCELLENT  0.009651  0.096557  ...

                carbon  deroot  detrunk  mulched  burnt  xpos  ypos  est_age  \
Step AgentID
50   5814     0.025706     0.0      0.0      0.0    0.0     4    68        1
     5815     0.029734     0.0      0.0      0.0    0.0    38    32        1
     5816     0.133383     0.0      0.0      0.0    0.0    19    40        1
     5817     0.122340     0.0      0.0      0.0    0.0    43    13        1
     5818     0.048278     0.0      0.0      0.0    0.0    17    71        1

                    lat       lng
Step AgentID
50   5814     51.497543 -0.169480
     5815     51.497209 -0.169011
     5816     51.497286 -0.169283
     5817     51.497037 -0.168949
     5818     51.497569 -0.169300

[5 rows x 21 columns]